# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoCalc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'BigNumber', :git => 'https://github.com/mkrd/Swift-Big-Integer.git'
  pod 'Repeat'

  # Pods for DemoCalc

  target 'DemoCalcTests' do
    inherit! :search_paths
	pod 'Quick'
	pod 'Nimble'
  end

end
